version: '3'

volumes:
  postgres-data:
    name: rails_postgres-data
  mysql-data:
    name: littlesis-wordpress-data
  # wordpress-html:
  #   name: littlesis-wordpress-html

networks:
  default:
    name: littlesis

services:
  app:
    image: littlesis:latest
    stdin_open: true
    tty: true
    init: true
    shm_size: '2gb'
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:3035:3035"
    volumes:
      - ./:/littlesis
    depends_on:
      - redis
      - postgres
    environment:
      - RAILS_ENV=development
      - LITTLESIS_BIND=tcp://0.0.0.0:8080
      - RAILS_SERVE_STATIC_FILES=true
      - WEB_CONCURRENCY=1
    extra_hosts:
      - "test.host:127.0.0.1"

  redis:
    image: redis:6

  postgres:
    image: postgres:13
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    shm_size: '2gb'
    volumes:
      - ./config/docker/postgresql.conf:/etc/postgresql.conf
      - ./data:/data
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-themanbehindthemanbehindthethrone}"
      POSTGRES_USER: "${POSTGRES_USER:-littlesis}"
      POSTGRES_DB: "${POSTGRES_DB:-littlesis}"

  nginx:
    image: nginx:latest
    ports:
       - "127.0.0.1:8081:80"
       - "127.0.0.1:9000:9000"
    volumes:
      - ./:/littlesis
      # - ./wordpress:/wordpress
      - ./config/docker/nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      # - ./static:/var/www/
    links:
      - app
      # - wordpress

  # mysql:
  #   image: mariadb:latest
  #   ports:
  #      - "127.0.0.1:3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   environment:
  #     MARIADB_ROOT_PASSWORD: eyesontheties

  # wordpress:
  #   image: littlesis-wordpress:latest
  #   volumes:
  #     - ./wordpress:/wordpress
  #   depends_on:
  #     - mysql
  #   environment:
  #     WORDPRESS_DEBUG: 'TRUE'
  #     WORDPRESS_DB_HOST: mysql
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress
  #     WORDPRESS_DB_NAME: wordpress
