version: "3"

# 8080 app
# 8081 nginx
# 8086 manticore
# 8088 manticore
# 8090 db
# 8091 replica
# 8888 jsserver

services:
  app:
    image: littlesis:latest
    shm_size: "2gb"
    ports:
      - "8080:8080"
    volumes:
      - ./:/littlesis
    environment:
      - LITTLESIS_BIND=tcp://0.0.0.0:8080
      - RAILS_SERVE_STATIC_FILES=true

  redis:
    image: docker.io/library/redis:6

  postgres:
    image: docker.io/library/postgres:15
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    shm_size: "2gb"
    volumes:
      - ./config/docker/pg-setup-database.sh:/docker-entrypoint-initdb.d/pg-setup-database.sh
      - ./config/docker/postgresql.conf:/etc/postgresql.conf
      - ./db/postgresql/primary:/var/lib/postgresql/data
      - ./db/postgresql/archive:/archive
      - ./data:/data
    ports:
      - "8090:5432"
    environment:
      POSTGRES_PASSWORD: "littlesis"

  # replica:
  #   image: docker.io/library/postgres:15
  #   command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
  # volumes:
  #   - ./config/docker/postgresql.conf:/etc/postgresql.conf
  #   - ./data:/data
  #   - ./db/postgresql/archive:/archive
  #   - ./db/postgresql/replica:/var/lib/postgresql/data
  #   ports:
  #     - "8091:5432"
  #   environment:
  #     POSTGRES_PASSWORD: "littlesis"

  nginx:
    image: docker.io/library/nginx:latest
    volumes:
      - ./public:/littlesis/public
    ports:
     - 8081:80

  manticore:
    image: littlesis:latest
    shm_size: "512mb"
    command: ["searchd", "--nodetach", "--config", "/etc/manticore.conf"]
    ports:
     - 8086:9306
     - 8088:9308
    volumes:
      - ./:/littlesis
      - ./config/development.sphinx.conf:/etc/manticore.conf
      - /home/ziggy/code/public-accountability/littlesis-rails/log:/home/ziggy/code/public-accountability/littlesis-rails/log

  esbuild:
    image: littlesis:latest
    command: ["npm", "run", "build-watch"]
    volumes:
      - ./:/littlesis
    depends_on:
      - app

  jsserver:
    image: jsserver:latest
    build: ./lib/js/server
    depends_on:
      - app
