version: 2.1

workflows:
  run_tests:
    jobs:
      - mocha
      - rspec
jobs:
  rspec:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true

    environment:
      RAILS_ENV: test

    steps:
      - checkout
      - run: bin/littlesis setup-folders
      - run: bin/littlesis build
      - run: bin/littlesis up
      - run: bin/littlesis docker -- exec postgres pg_isready --timeout=10
      - run: bin/littlesis --test rake db:reset
      - run: bin/littlesis --test rake javascript:build
      - run: bin/littlesis --test rake assets:precompile
      - run: bin/littlesis --test test -- --format documentation --format RspecJunitFormatter -o ./tmp/rspec/rspec.xml
      - store_test_results:
          path: tmp/rspec

  mocha:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: npm test
