version: 2.1

jobs:
  rspec:
    machine:
      image: ubuntu-2004:202107-02
#      docker_layer_caching: true
    environment:
      RAILS_ENV: test
      COVERAGE: yes
      POSTGRES_PASSWORD: littlesis
      POSTGRES_USER: littlesis
      POSTGRES_DB: littlesis_test
    resource_class: medium
    steps:
      - checkout
      - run: cp config/database.ci.yml config/database.yml
      - run: mkdir -p tmp tmp/rspec tmp/small/ tmp/profile tmp/large/ tmp/original/
      - run: docker build -t littlesis:latest .
      - run: docker-compose up -d
      - run: docker-compose exec postgres pg_isready --timeout=10
      - run: docker-compose exec app bundle exec rake db:reset
      - run: docker-compose exec app bundle exec rake tmp:clear
      - run: docker-compose exec app bundle exec rake assets:precompile
      - run: docker-compose exec app bundle exec rspec --format documentation --format RspecJunitFormatter -o ./tmp/rspec/rspec.xml

      - store_test_results:
          path: tmp/rspec

      - store_artifacts:
          path: coverage

  mocha:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --immutable

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn test

workflows:
  rspec:
    jobs:
      - rspec
      - mocha
