version: 2.1

jobs:
  rspec:
    docker:
      - image: ruby:2.7.2-buster
        environment:
          RAILS_ENV: test
      - image: circleci/mariadb:10.5-focal
        environment:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout
      - run: bin/ci_setup.sh
      - run: bin/docker_setup.sh
      - run: bin/wait_for_mariadb.sh
      - run: bin/mariadb_setup.sh
      - run: bundle install
      - run: bundle exec rake db:structure:load
      - run: bundle exec rake db:seed
      - run: bundle exec rake assets:precompile
      - run: bundle exec rspec

workflows:
  rspec:
    jobs:
      - rspec
