defaults: &defaults
  # morphology: stem_en
  query_log_min_msec: 200
  min_infix_len: 3
  min_word_len: 1
  charset_table: non_cjk
  html_strip: true
  mem_limit:  512M

test:
  <<: *defaults
  mysql41: 9307
  mem_limit:  1024M
  batch_size: 10000

development:
  <<: *defaults
  address: manticore
  mysql41: 9312

production:
  <<: *defaults
  socket: "/var/www/littlesis/tmp/production.sphinx"
